#
# Docker Compose settings for development
#
version: "3"

services:

  app:
    build: .
    environment:
      - DB_DIALECT=postgresql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    build: https://github.com/m-martinez/pg-audit-json.git#1.0.2
    expose:
      - "5432"
    tmpfs: /var/lib/postgresql/data
