# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 07:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('schema_name', models.TextField()),
                ('table_name', models.TextField()),
                ('relid', models.IntegerField()),
                ('session_user_name', models.TextField()),
                ('current_user_name', models.TextField()),
                ('action_tstamp_tx', models.DateTimeField()),
                ('action_tstamp_stm', models.DateTimeField()),
                ('action_tstamp_clk', models.DateTimeField()),
                ('transaction_id', models.BigIntegerField()),
                ('client_addr', models.GenericIPAddressField()),
                ('client_query', models.TextField()),
                ('application_name', models.TextField()),
                ('application_user_name', models.TextField()),
                ('action', models.TextField()),
                ('row_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('changed_fields', django.contrib.postgres.fields.jsonb.JSONField()),
                ('statement_only', models.BooleanField()),
            ],
            options={
                'db_table': '"audit"."log"',
                'managed': False,
            },
        ),
    ]
